# Isolated Network
networks:
  agent_private_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/16

# Target Service
services:
  target_server:
    container_name: rarat_target_server
    image: bkimminich/juice-shop:latest
    hostname: target.internal
    ports:
      - "3000:3000"
    networks:
      agent_private_network:
        ipv4_address: 172.28.0.10
    environment:
      - NODE_ENV=production
    restart: always


# Agent Sandbox
  agent_sandbox:
    container_name: rarat_agent_sandbox
    image: rarat_sandbox_base
    networks:
      agent_private_network:
        ipv4_address: 172.28.0.20

    volumes:
      - ${PROJECT_ROOT}/sandbox_data:/sandbox

    working_dir: /sandbox

    command: ["/usr/bin/tail", "-f", "/dev/null"]
    depends_on:
      - target_server #Make sure the target server is running