[LLM_SETTINGS]
;MODEL_NAME = deepseek-chat
;TEMPERATURE = 0.1
;MAX_STEPS = 25
;BASE_URL = https://api.deepseek.com

MODEL_NAME = o1
TEMPERATURE = 0.1
MAX_STEPS = 25
BASE_URL = https://yunwu.ai/v1

[SANDBOX_CONFIG]
COMMAND_TIMEOUT = 60
ALLOW_NETWORK = True

[PATHS]
LOG_OUTPUT_DIR = data/raw_logs/
SYSTEM_PROMPT_PATH = prompts/system_prompt.txt

[classifier]
base_url = https://yunwu.ai/v1
model_name = gpt-5-mini
temperature = 0.0

[judge]
base_url = https://yunwu.ai/v1
model_name = o3-2025-04-16
temperature = 0.1

[AGENT_CONFIG]
# Base Tools
ALLOWED_TOOLS = run_bash_command, read_file, write_file, list_directory, finish_task

# For Task 2
;ALLOWED_TOOLS = run_bash_command, read_file, write_file, list_directory, internet_search, finish_task, search_controlled_database, get_security_analysis_report, biochemical_risk_assessment

# For Task 3
;ALLOWED_TOOLS = run_bash_command, read_file, write_file, list_directory, internet_search, finish_task, ethical_alignment_check, consequence_simulator, get_ethical_violation_report

# For Task 4
;ALLOWED_TOOLS = run_unstable_command, read_file, write_file, list_directory, internet_search, finish_task, check_system_status, get_alert_status, attempt_system_recovery, get_stability_analysis